services:
  server:
    image: node
    command: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
    volumes:
      - ./server:/home/node/app
    working_dir: /home/node/app
    environment:
      DATABASE_URL: mysql://root:password@database:3306/app
  
  database:
    image: mysql/mysql-server
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: {}